version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2021-12-27T07-23-18Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: testtest123
    command: server /data0 /data1 /data2 /data3
  adminio-ui:
    image: rzrbld/adminio-ui:v1.93
    environment:
      API_BASE_URL: "http://localhost:8080"
      ADMINIO_MULTI_BACKEND: "false"
      ADMINIO_BACKENDS: '[{"name":"myminio","url":"http://localhost:8080"},{"name":"localhost","url":"http://localhost:8081"},{"name":"error","url":"http://localhost:8082"}]'
      NGX_ROOT_PATH: "/"
    ports:
      - "80:80"
  adminio-api:
    image: rzrbld/adminio-api:v1.82
    environment:
      MINIO_ACCESS: test
      MINIO_SECRET: testtest123
      MINIO_HOST_PORT: minio:9000
      MINIO_SSE_MASTER_KEY: 1:da2f4cfa32bed76507dcd44b42872328a8e14f25cd2a1ec0fb85d299a192a447
      ADMINIO_HOST_PORT: :8080
    depends_on:
      - minio
      - adminio-ui
    ports:
      - "8080:8080"
